# Generated by Django 5.1.3 on 2024-12-12 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_teacher_avatar_userprofile_avatar'),
    ]

    operations = [
    ]
