# Generated by Django 5.1.3 on 2024-12-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_rating_availability_rating_methodology_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='score',
        ),
        migrations.AlterField(
            model_name='rating',
            name='availability',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Оценка доступности преподавателя от 1 до 5'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='methodology',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Оценка методологии преподавания от 1 до 5'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='teaching_quality',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Оценка качества преподавания от 1 до 5'),
        ),
    ]
